### ISSUE TITLE
Check for root privileges, don't use sudo

### ISSUE THREAD

**Issue by codygarver** [tylerhammer/grafana#1]
It's poor practice to use sudo in a script. Instead, you should check for root privileges and exit with an error if they aren't found.

Something like this would work:
```
check_your_privilege () {
    if [[ "$(id -u)" != 0 ]]; then
        echo "E: Requires root permissions" > /dev/stderr
        exit 1
    fi
}
check_your_privilege
```

**Comment by tylerhammer** [comment]
I assume you would run something like this at the beginning of the script?

**Comment by codygarver** [comment]
That's right, first thing.

**Comment by tylerhammer** [comment]
Okay fair enough. I'll give it a test and update it.

**Comment by codygarver** [comment]
I definitely understand, it's fine if you don't wanna change it. Just something I noticed when perusing through the code.

**Comment by tylerhammer** [comment]
I have no problem with updating the code. I'm not a "scripter". This was something that I just googled as I went about it. I appreciate the recommendation!

**Comment by tylerhammer** [comment]
Tested and confirmed working. 

Appreciate the great addition to the script!
