### ISSUE TITLE
Virtual Machine install

### ISSUE THREAD

**Issue by bntjah** [tylerhammer/grafana#2]
If you installed the vm as a virtual machine mode you need to install apt-transport-https otherwise your script won't work... perhaps you need to build in a few checks to see if everything is installed and if not install it before continuing? ;-)

**Comment by tylerhammer** [comment]
I'm not sure I follow? I install Ubuntu on my ESXi as a VM, and have no issues.

**Comment by bntjah** [comment]
I think you are missing the apt-transport-https when you install your VM you have the option for modes I think its F6 and you can choose a minimal virtual machine and then it skips a few packages one of wich you need is the apt-transport-https

**Comment by tylerhammer** [comment]
I've never had that issue, but I'll definitely take a look at adding in some checks to be safe.

**Comment by tylerhammer** [comment]
Can you think of any other dependencies that are needed ?

**Comment by bntjah** [comment]
I am currently running it on a fresh installed vm with vm mode on; so if I find something I'll just post in this issue not to clutter your github.

**Comment by tylerhammer** [comment]
Appreciate it!

**Comment by bntjah** [comment]
./install.sh: line 148: logout: not login shell: use `exit'
saw this once before when I initially ran the script and noticed (following your tutorial) that something didn't work

**Comment by tylerhammer** [comment]
Yeah, I have updated that recently. I just have not pushed it yet.

**Comment by bntjah** [comment]
After I ran this manually;:
sudo usermod -aG docker $(whoami)

$ docker ps -a
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.25/containers/json?all=1: dial unix /var/run/docker.sock: connect: permission denied

Trying to figure out whats going on here

**Comment by tylerhammer** [comment]
For that issue, its why there is a reboot at the end of the script. That command requires you to log out and log back in to apply it, so instead, I just reboot the entire VM.

**Comment by bntjah** [comment]
gvw@Grafana:~$ systemctl status esximon.service -l
● esximon.service - ESXi Stats
   Loaded: loaded (/lib/systemd/system/esximon.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
gvw@Grafana:~$ sudo service esximon start
gvw@Grafana:~$ systemctl status esximon.service -l
● esximon.service - ESXi Stats
   Loaded: loaded (/lib/systemd/system/esximon.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2017-02-08 19:56:51 CET; 1s ago
  Process: 22474 ExecStart=/bin/bash -x esxi.sh (code=exited, status=127)
 Main PID: 22474 (code=exited, status=127)

Feb 08 19:56:51 Grafana systemd[1]: Started ESXi Stats.
Feb 08 19:56:51 Grafana systemd[1]: esximon.service: Main process exited, code=exited, status=127/n/a
Feb 08 19:56:51 Grafana systemd[1]: esximon.service: Unit entered failed state.
Feb 08 19:56:51 Grafana systemd[1]: esximon.service: Failed with result 'exit-code'.

**Comment by tylerhammer** [comment]
Couple things to check there is if it created the cfg file.

**Comment by bntjah** [comment]
#####################################
#                                   #
# Configuration File for ESXi.sh    #
#                                   #
# Created by github.com/tylerhammer #
#                                   #
#####################################

# Host name of ESXi
HOST=Host

# ESXi Host IP
ESXIP=esxiip

# ESXi Root Username
ROOT=root

# ESXI Root Password
PASSWORD=SuperSecret

# InfluxDB IP
INFLUXIP=

# Name of Database
DATABASE=esxi.fsociety

# Interval between polls (In seconds)
INTERVAL=5

**Comment by tylerhammer** [comment]
Okay, I assume you filled in your influxIP correct? Also, I dont think Influx likes database names with a . in them.

**Comment by bntjah** [comment]
Sec; lets give that a try and I did enter it but somehow didn't get used; will quickly check with this

**Comment by tylerhammer** [comment]
Okay. Can you run the script manually, outside of the service and tell me what it outputs?

**Comment by bntjah** [comment]
Does ssh need to be activated on the esxi? Might be interesting to tell this...

**Comment by tylerhammer** [comment]
SSH and SNMP need to be enabled. I will definitely add that into tell people.

**Comment by bntjah** [comment]
Apparently curl is also not installed when installing in vm mode

**Comment by tylerhammer** [comment]
How are you installing it in VM mode? I'll have to set up one so I can test on it.

**Comment by bntjah** [comment]
Choose language
Press F4 to get to modes
And then put it on Install a minimal virtual machine
Then just install Ubuntu Server

**Comment by tylerhammer** [comment]
I'll test this out soon.

**Comment by bntjah** [comment]
I'm also running in to the fact that the database doesn't exist on influx and can't seem to create it as bash won't find the influx command o.0

**Comment by tylerhammer** [comment]
what influx command? And what are you naming your databases when you run the script?

**Comment by bntjah** [comment]
Wich script? The esxi.sh just asks me what I named the database but I reran your script a few times and didn't ask for something or I'm just an idiot (also possible)

**Comment by tylerhammer** [comment]
Sorry, when you're running the esxi_setup.sh script, it asks you what you'd like to name the database. If the database doesnt exist, it creates it for you.

**Comment by bntjah** [comment]
Ok; I'm restarting from scratch here without the virtual mode; lets see how this goes

**Comment by tylerhammer** [comment]
Let me know!

**Comment by bntjah** [comment]
Goes in to some sort of loop; doesn't do what its supposed to do... but I'll look into this tomorrow as I'm kind of tired and not really wanting to see this screen again xD

**Comment by tylerhammer** [comment]
More information would be helpful. As in what kind of loop you're talking about and what its actually doing.

**Comment by bntjah** [comment]
Its actually asking me to update wether I say yes or no it goes on reboots; but no docker is installed and don't this a few times but now appears to be working :S

**Comment by bntjah** [comment]
I'm going to close this issue and continue over mail wich will be easier and less intrusive later on
