### ISSUE TITLE
Ubuntu 18.04 Server Repositories

### ISSUE THREAD

**Issue by JohnFedorchak** [tylerhammer/grafana#6]
For a standard Ubuntu 18.04 Server install, both universe and multiverse are missing, which means that **sshpass** and **snmp-mibs-downloader** both fail to install.

Recommend prompting to enable these repositories, or at the bare minimum making it a pre-requisite in the instructions or script!

I'm new to Ubuntu and it took me a while to figure this out, even though install.log told me exactly what was wrong.

`sudo apt-add-repository universe`
`sudo apt-add-repository multiverse`

**Comment by tylerhammer** [comment]
Thank you for your feedback. This script was created purely with Ubuntu 16.04 in mind. As mentioned in the guide, your mileage may vary with other version. 

I am also no longer maintaining repository. 

Thanks
